### ISSUE TITLE
弱弱的问一句。。。这个咋使用？

### ISSUE THREAD

**Issue by smart-z** [lcandy2/oSearch#1]
试了一个在列表名单内的网站比如v2ex，结果什么都没有发生，我一头雾水，回头来检测自己的智商。。。就比如是怎么把当前支持的网站加入opensearch？看不到那里可以加入。点oSearch，就告诉我oSearch正在运行。。。求指教。

**Comment by nexmoe** [comment]
访问完了 v2ex.com 后，在地址栏输入 v2ex.com 然后按一下 tab 键
